version: "3.8"
services:
  node:
    container_name: nodejs    
    build: .
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - SERVER_PORT=8080
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/enviame
    volumes:
      - ./:/code
  mongo:
    container_name: mongodb
    image: mongo    
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017" 
  